# Render deployment configuration
version: 2
services:
  - type: web
    name: housemate-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true